spring.datasource.url=jdbc:postgresql://localhost:5432/apilibrary
spring.datasource.username=postgres
spring.datasource.password=Tajetti08

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

security.jwt.secret=8f4c2a91d7e64b3fa2c1e8d9a7b6c5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b
security.jwt.expiration-ms=3600000